/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapJobsDotxmlRouteImport } from './routes/sitemap-jobs[.]xml'
import { Route as SitemapHubsDotxmlRouteImport } from './routes/sitemap-hubs[.]xml'
import { Route as SitemapCoreDotxmlRouteImport } from './routes/sitemap-core[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RefundCancellationRouteImport } from './routes/refund-cancellation'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtsCheckerRouteImport } from './routes/ats-checker'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeTemplatesIndexRouteImport } from './routes/resume-templates.index'
import { Route as ResumeBundlesIndexRouteImport } from './routes/resume-bundles.index'
import { Route as DmatResourcesIndexRouteImport } from './routes/dmat-resources.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AtsResumesPackIndexRouteImport } from './routes/ats-resumes-pack.index'
import { Route as AtsFriendlyResumesIndexRouteImport } from './routes/ats-friendly-resumes.index'
import { Route as SearchAdminRouteImport } from './routes/search_.admin'
import { Route as ResumeTemplatesSlugRouteImport } from './routes/resume-templates.$slug'
import { Route as ResumeBundlesSlugRouteImport } from './routes/resume-bundles.$slug'
import { Route as LocationSlugRouteImport } from './routes/location.$slug'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AtsResumesPackSlugRouteImport } from './routes/ats-resumes-pack.$slug'
import { Route as AtsFriendlyResumesSlugRouteImport } from './routes/ats-friendly-resumes.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DmatResourcesPacksIndexRouteImport } from './routes/dmat-resources.packs.index'
import { Route as DmatResourcesModulesIndexRouteImport } from './routes/dmat-resources.modules.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PaymentSuccessOrderIdRouteImport } from './routes/payment.success.$orderId'
import { Route as DmatResourcesPacksSlugRouteImport } from './routes/dmat-resources.packs.$slug'
import { Route as DmatResourcesModulesSlugRouteImport } from './routes/dmat-resources.modules.$slug'
import { Route as CheckoutBundleSlugRouteImport } from './routes/checkout.bundle.$slug'
import { Route as AuthenticatedAdminSiteSettingsRouteImport } from './routes/_authenticated/admin.site-settings'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminResumeBundlesRouteImport } from './routes/_authenticated/admin.resume-bundles'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin.feedback'
import { Route as AuthenticatedAdminAtsSettingsRouteImport } from './routes/_authenticated/admin.ats-settings'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminResumeTemplatesIndexRouteImport } from './routes/_authenticated/admin.resume-templates.index'
import { Route as AuthenticatedAdminResumePacksIndexRouteImport } from './routes/_authenticated/admin.resume-packs.index'
import { Route as AuthenticatedAdminDmatModuleIndexRouteImport } from './routes/_authenticated/admin.dmat-module.index'
import { Route as AuthenticatedAdminDmatCompleteIndexRouteImport } from './routes/_authenticated/admin.dmat-complete.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminResumeTemplatesNewRouteImport } from './routes/_authenticated/admin.resume-templates.new'
import { Route as AuthenticatedAdminResumePacksNewRouteImport } from './routes/_authenticated/admin.resume-packs.new'
import { Route as AuthenticatedAdminJobsNewRouteImport } from './routes/_authenticated/admin.jobs.new'
import { Route as AuthenticatedAdminJobsBulkRouteImport } from './routes/_authenticated/admin.jobs.bulk'
import { Route as AuthenticatedAdminJobsAuditRouteImport } from './routes/_authenticated/admin.jobs.audit'
import { Route as AuthenticatedAdminDmatModuleNewRouteImport } from './routes/_authenticated/admin.dmat-module.new'
import { Route as AuthenticatedAdminDmatCompleteNewRouteImport } from './routes/_authenticated/admin.dmat-complete.new'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin.blog.new'
import { Route as AuthenticatedAdminResumeTemplatesIdIndexRouteImport } from './routes/_authenticated/admin.resume-templates.$id.index'
import { Route as AuthenticatedAdminResumePacksIdIndexRouteImport } from './routes/_authenticated/admin.resume-packs.$id.index'
import { Route as AuthenticatedAdminDmatModuleIdIndexRouteImport } from './routes/_authenticated/admin.dmat-module.$id.index'
import { Route as AuthenticatedAdminDmatCompleteIdIndexRouteImport } from './routes/_authenticated/admin.dmat-complete.$id.index'
import { Route as AuthenticatedAdminResumeTemplatesIdEditRouteImport } from './routes/_authenticated/admin.resume-templates.$id.edit'
import { Route as AuthenticatedAdminResumePacksIdEditRouteImport } from './routes/_authenticated/admin.resume-packs.$id.edit'
import { Route as AuthenticatedAdminJobsSlugEditRouteImport } from './routes/_authenticated/admin.jobs.$slug.edit'
import { Route as AuthenticatedAdminDmatModuleIdEditRouteImport } from './routes/_authenticated/admin.dmat-module.$id.edit'
import { Route as AuthenticatedAdminDmatCompleteIdEditRouteImport } from './routes/_authenticated/admin.dmat-complete.$id.edit'
import { Route as AuthenticatedAdminBlogIdEditRouteImport } from './routes/_authenticated/admin.blog.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapJobsDotxmlRoute = SitemapJobsDotxmlRouteImport.update({
  id: '/sitemap-jobs.xml',
  path: '/sitemap-jobs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapHubsDotxmlRoute = SitemapHubsDotxmlRouteImport.update({
  id: '/sitemap-hubs.xml',
  path: '/sitemap-hubs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCoreDotxmlRoute = SitemapCoreDotxmlRouteImport.update({
  id: '/sitemap-core.xml',
  path: '/sitemap-core.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationRoute = RefundCancellationRouteImport.update({
  id: '/refund-cancellation',
  path: '/refund-cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsCheckerRoute = AtsCheckerRouteImport.update({
  id: '/ats-checker',
  path: '/ats-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplatesIndexRoute = ResumeTemplatesIndexRouteImport.update({
  id: '/resume-templates/',
  path: '/resume-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBundlesIndexRoute = ResumeBundlesIndexRouteImport.update({
  id: '/resume-bundles/',
  path: '/resume-bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmatResourcesIndexRoute = DmatResourcesIndexRouteImport.update({
  id: '/dmat-resources/',
  path: '/dmat-resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsResumesPackIndexRoute = AtsResumesPackIndexRouteImport.update({
  id: '/ats-resumes-pack/',
  path: '/ats-resumes-pack/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsFriendlyResumesIndexRoute = AtsFriendlyResumesIndexRouteImport.update({
  id: '/ats-friendly-resumes/',
  path: '/ats-friendly-resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchAdminRoute = SearchAdminRouteImport.update({
  id: '/search_/admin',
  path: '/search/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplatesSlugRoute = ResumeTemplatesSlugRouteImport.update({
  id: '/resume-templates/$slug',
  path: '/resume-templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBundlesSlugRoute = ResumeBundlesSlugRouteImport.update({
  id: '/resume-bundles/$slug',
  path: '/resume-bundles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/location/$slug',
  path: '/location/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsResumesPackSlugRoute = AtsResumesPackSlugRouteImport.update({
  id: '/ats-resumes-pack/$slug',
  path: '/ats-resumes-pack/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsFriendlyResumesSlugRoute = AtsFriendlyResumesSlugRouteImport.update({
  id: '/ats-friendly-resumes/$slug',
  path: '/ats-friendly-resumes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DmatResourcesPacksIndexRoute = DmatResourcesPacksIndexRouteImport.update({
  id: '/dmat-resources/packs/',
  path: '/dmat-resources/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmatResourcesModulesIndexRoute =
  DmatResourcesModulesIndexRouteImport.update({
    id: '/dmat-resources/modules/',
    path: '/dmat-resources/modules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PaymentSuccessOrderIdRoute = PaymentSuccessOrderIdRouteImport.update({
  id: '/payment/success/$orderId',
  path: '/payment/success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DmatResourcesPacksSlugRoute = DmatResourcesPacksSlugRouteImport.update({
  id: '/dmat-resources/packs/$slug',
  path: '/dmat-resources/packs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DmatResourcesModulesSlugRoute =
  DmatResourcesModulesSlugRouteImport.update({
    id: '/dmat-resources/modules/$slug',
    path: '/dmat-resources/modules/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutBundleSlugRoute = CheckoutBundleSlugRouteImport.update({
  id: '/checkout/bundle/$slug',
  path: '/checkout/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSiteSettingsRoute =
  AuthenticatedAdminSiteSettingsRouteImport.update({
    id: '/site-settings',
    path: '/site-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeBundlesRoute =
  AuthenticatedAdminResumeBundlesRouteImport.update({
    id: '/resume-bundles',
    path: '/resume-bundles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAtsSettingsRoute =
  AuthenticatedAdminAtsSettingsRouteImport.update({
    id: '/ats-settings',
    path: '/ats-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesIndexRoute =
  AuthenticatedAdminResumeTemplatesIndexRouteImport.update({
    id: '/resume-templates/',
    path: '/resume-templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumePacksIndexRoute =
  AuthenticatedAdminResumePacksIndexRouteImport.update({
    id: '/resume-packs/',
    path: '/resume-packs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatModuleIndexRoute =
  AuthenticatedAdminDmatModuleIndexRouteImport.update({
    id: '/dmat-module/',
    path: '/dmat-module/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatCompleteIndexRoute =
  AuthenticatedAdminDmatCompleteIndexRouteImport.update({
    id: '/dmat-complete/',
    path: '/dmat-complete/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesNewRoute =
  AuthenticatedAdminResumeTemplatesNewRouteImport.update({
    id: '/resume-templates/new',
    path: '/resume-templates/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumePacksNewRoute =
  AuthenticatedAdminResumePacksNewRouteImport.update({
    id: '/resume-packs/new',
    path: '/resume-packs/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsNewRoute =
  AuthenticatedAdminJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsBulkRoute =
  AuthenticatedAdminJobsBulkRouteImport.update({
    id: '/jobs/bulk',
    path: '/jobs/bulk',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsAuditRoute =
  AuthenticatedAdminJobsAuditRouteImport.update({
    id: '/jobs/audit',
    path: '/jobs/audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatModuleNewRoute =
  AuthenticatedAdminDmatModuleNewRouteImport.update({
    id: '/dmat-module/new',
    path: '/dmat-module/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatCompleteNewRoute =
  AuthenticatedAdminDmatCompleteNewRouteImport.update({
    id: '/dmat-complete/new',
    path: '/dmat-complete/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/blog/new',
    path: '/blog/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesIdIndexRoute =
  AuthenticatedAdminResumeTemplatesIdIndexRouteImport.update({
    id: '/resume-templates/$id/',
    path: '/resume-templates/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumePacksIdIndexRoute =
  AuthenticatedAdminResumePacksIdIndexRouteImport.update({
    id: '/resume-packs/$id/',
    path: '/resume-packs/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatModuleIdIndexRoute =
  AuthenticatedAdminDmatModuleIdIndexRouteImport.update({
    id: '/dmat-module/$id/',
    path: '/dmat-module/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatCompleteIdIndexRoute =
  AuthenticatedAdminDmatCompleteIdIndexRouteImport.update({
    id: '/dmat-complete/$id/',
    path: '/dmat-complete/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesIdEditRoute =
  AuthenticatedAdminResumeTemplatesIdEditRouteImport.update({
    id: '/resume-templates/$id/edit',
    path: '/resume-templates/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumePacksIdEditRoute =
  AuthenticatedAdminResumePacksIdEditRouteImport.update({
    id: '/resume-packs/$id/edit',
    path: '/resume-packs/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsSlugEditRoute =
  AuthenticatedAdminJobsSlugEditRouteImport.update({
    id: '/jobs/$slug/edit',
    path: '/jobs/$slug/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatModuleIdEditRoute =
  AuthenticatedAdminDmatModuleIdEditRouteImport.update({
    id: '/dmat-module/$id/edit',
    path: '/dmat-module/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDmatCompleteIdEditRoute =
  AuthenticatedAdminDmatCompleteIdEditRouteImport.update({
    id: '/dmat-complete/$id/edit',
    path: '/dmat-complete/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIdEditRoute =
  AuthenticatedAdminBlogIdEditRouteImport.update({
    id: '/blog/$id/edit',
    path: '/blog/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/search': typeof SearchRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-hubs.xml': typeof SitemapHubsDotxmlRoute
  '/sitemap-jobs.xml': typeof SitemapJobsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ats-friendly-resumes/$slug': typeof AtsFriendlyResumesSlugRoute
  '/ats-resumes-pack/$slug': typeof AtsResumesPackSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/resume-bundles/$slug': typeof ResumeBundlesSlugRoute
  '/resume-templates/$slug': typeof ResumeTemplatesSlugRoute
  '/search/admin': typeof SearchAdminRoute
  '/ats-friendly-resumes/': typeof AtsFriendlyResumesIndexRoute
  '/ats-resumes-pack/': typeof AtsResumesPackIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dmat-resources/': typeof DmatResourcesIndexRoute
  '/resume-bundles/': typeof ResumeBundlesIndexRoute
  '/resume-templates/': typeof ResumeTemplatesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/ats-settings': typeof AuthenticatedAdminAtsSettingsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/resume-bundles': typeof AuthenticatedAdminResumeBundlesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/checkout/bundle/$slug': typeof CheckoutBundleSlugRoute
  '/dmat-resources/modules/$slug': typeof DmatResourcesModulesSlugRoute
  '/dmat-resources/packs/$slug': typeof DmatResourcesPacksSlugRoute
  '/payment/success/$orderId': typeof PaymentSuccessOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dmat-resources/modules/': typeof DmatResourcesModulesIndexRoute
  '/dmat-resources/packs/': typeof DmatResourcesPacksIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/dmat-complete/new': typeof AuthenticatedAdminDmatCompleteNewRoute
  '/admin/dmat-module/new': typeof AuthenticatedAdminDmatModuleNewRoute
  '/admin/jobs/audit': typeof AuthenticatedAdminJobsAuditRoute
  '/admin/jobs/bulk': typeof AuthenticatedAdminJobsBulkRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/admin/resume-packs/new': typeof AuthenticatedAdminResumePacksNewRoute
  '/admin/resume-templates/new': typeof AuthenticatedAdminResumeTemplatesNewRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/dmat-complete/': typeof AuthenticatedAdminDmatCompleteIndexRoute
  '/admin/dmat-module/': typeof AuthenticatedAdminDmatModuleIndexRoute
  '/admin/resume-packs/': typeof AuthenticatedAdminResumePacksIndexRoute
  '/admin/resume-templates/': typeof AuthenticatedAdminResumeTemplatesIndexRoute
  '/admin/blog/$id/edit': typeof AuthenticatedAdminBlogIdEditRoute
  '/admin/dmat-complete/$id/edit': typeof AuthenticatedAdminDmatCompleteIdEditRoute
  '/admin/dmat-module/$id/edit': typeof AuthenticatedAdminDmatModuleIdEditRoute
  '/admin/jobs/$slug/edit': typeof AuthenticatedAdminJobsSlugEditRoute
  '/admin/resume-packs/$id/edit': typeof AuthenticatedAdminResumePacksIdEditRoute
  '/admin/resume-templates/$id/edit': typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  '/admin/dmat-complete/$id/': typeof AuthenticatedAdminDmatCompleteIdIndexRoute
  '/admin/dmat-module/$id/': typeof AuthenticatedAdminDmatModuleIdIndexRoute
  '/admin/resume-packs/$id/': typeof AuthenticatedAdminResumePacksIdIndexRoute
  '/admin/resume-templates/$id/': typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/search': typeof SearchRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-hubs.xml': typeof SitemapHubsDotxmlRoute
  '/sitemap-jobs.xml': typeof SitemapJobsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/ats-friendly-resumes/$slug': typeof AtsFriendlyResumesSlugRoute
  '/ats-resumes-pack/$slug': typeof AtsResumesPackSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/resume-bundles/$slug': typeof ResumeBundlesSlugRoute
  '/resume-templates/$slug': typeof ResumeTemplatesSlugRoute
  '/search/admin': typeof SearchAdminRoute
  '/ats-friendly-resumes': typeof AtsFriendlyResumesIndexRoute
  '/ats-resumes-pack': typeof AtsResumesPackIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dmat-resources': typeof DmatResourcesIndexRoute
  '/resume-bundles': typeof ResumeBundlesIndexRoute
  '/resume-templates': typeof ResumeTemplatesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/ats-settings': typeof AuthenticatedAdminAtsSettingsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/resume-bundles': typeof AuthenticatedAdminResumeBundlesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/checkout/bundle/$slug': typeof CheckoutBundleSlugRoute
  '/dmat-resources/modules/$slug': typeof DmatResourcesModulesSlugRoute
  '/dmat-resources/packs/$slug': typeof DmatResourcesPacksSlugRoute
  '/payment/success/$orderId': typeof PaymentSuccessOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dmat-resources/modules': typeof DmatResourcesModulesIndexRoute
  '/dmat-resources/packs': typeof DmatResourcesPacksIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/dmat-complete/new': typeof AuthenticatedAdminDmatCompleteNewRoute
  '/admin/dmat-module/new': typeof AuthenticatedAdminDmatModuleNewRoute
  '/admin/jobs/audit': typeof AuthenticatedAdminJobsAuditRoute
  '/admin/jobs/bulk': typeof AuthenticatedAdminJobsBulkRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/admin/resume-packs/new': typeof AuthenticatedAdminResumePacksNewRoute
  '/admin/resume-templates/new': typeof AuthenticatedAdminResumeTemplatesNewRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/dmat-complete': typeof AuthenticatedAdminDmatCompleteIndexRoute
  '/admin/dmat-module': typeof AuthenticatedAdminDmatModuleIndexRoute
  '/admin/resume-packs': typeof AuthenticatedAdminResumePacksIndexRoute
  '/admin/resume-templates': typeof AuthenticatedAdminResumeTemplatesIndexRoute
  '/admin/blog/$id/edit': typeof AuthenticatedAdminBlogIdEditRoute
  '/admin/dmat-complete/$id/edit': typeof AuthenticatedAdminDmatCompleteIdEditRoute
  '/admin/dmat-module/$id/edit': typeof AuthenticatedAdminDmatModuleIdEditRoute
  '/admin/jobs/$slug/edit': typeof AuthenticatedAdminJobsSlugEditRoute
  '/admin/resume-packs/$id/edit': typeof AuthenticatedAdminResumePacksIdEditRoute
  '/admin/resume-templates/$id/edit': typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  '/admin/dmat-complete/$id': typeof AuthenticatedAdminDmatCompleteIdIndexRoute
  '/admin/dmat-module/$id': typeof AuthenticatedAdminDmatModuleIdIndexRoute
  '/admin/resume-packs/$id': typeof AuthenticatedAdminResumePacksIdIndexRoute
  '/admin/resume-templates/$id': typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/search': typeof SearchRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-hubs.xml': typeof SitemapHubsDotxmlRoute
  '/sitemap-jobs.xml': typeof SitemapJobsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ats-friendly-resumes/$slug': typeof AtsFriendlyResumesSlugRoute
  '/ats-resumes-pack/$slug': typeof AtsResumesPackSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/resume-bundles/$slug': typeof ResumeBundlesSlugRoute
  '/resume-templates/$slug': typeof ResumeTemplatesSlugRoute
  '/search_/admin': typeof SearchAdminRoute
  '/ats-friendly-resumes/': typeof AtsFriendlyResumesIndexRoute
  '/ats-resumes-pack/': typeof AtsResumesPackIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dmat-resources/': typeof DmatResourcesIndexRoute
  '/resume-bundles/': typeof ResumeBundlesIndexRoute
  '/resume-templates/': typeof ResumeTemplatesIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/ats-settings': typeof AuthenticatedAdminAtsSettingsRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/resume-bundles': typeof AuthenticatedAdminResumeBundlesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/checkout/bundle/$slug': typeof CheckoutBundleSlugRoute
  '/dmat-resources/modules/$slug': typeof DmatResourcesModulesSlugRoute
  '/dmat-resources/packs/$slug': typeof DmatResourcesPacksSlugRoute
  '/payment/success/$orderId': typeof PaymentSuccessOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/dmat-resources/modules/': typeof DmatResourcesModulesIndexRoute
  '/dmat-resources/packs/': typeof DmatResourcesPacksIndexRoute
  '/_authenticated/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/_authenticated/admin/dmat-complete/new': typeof AuthenticatedAdminDmatCompleteNewRoute
  '/_authenticated/admin/dmat-module/new': typeof AuthenticatedAdminDmatModuleNewRoute
  '/_authenticated/admin/jobs/audit': typeof AuthenticatedAdminJobsAuditRoute
  '/_authenticated/admin/jobs/bulk': typeof AuthenticatedAdminJobsBulkRoute
  '/_authenticated/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/_authenticated/admin/resume-packs/new': typeof AuthenticatedAdminResumePacksNewRoute
  '/_authenticated/admin/resume-templates/new': typeof AuthenticatedAdminResumeTemplatesNewRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/dmat-complete/': typeof AuthenticatedAdminDmatCompleteIndexRoute
  '/_authenticated/admin/dmat-module/': typeof AuthenticatedAdminDmatModuleIndexRoute
  '/_authenticated/admin/resume-packs/': typeof AuthenticatedAdminResumePacksIndexRoute
  '/_authenticated/admin/resume-templates/': typeof AuthenticatedAdminResumeTemplatesIndexRoute
  '/_authenticated/admin/blog/$id/edit': typeof AuthenticatedAdminBlogIdEditRoute
  '/_authenticated/admin/dmat-complete/$id/edit': typeof AuthenticatedAdminDmatCompleteIdEditRoute
  '/_authenticated/admin/dmat-module/$id/edit': typeof AuthenticatedAdminDmatModuleIdEditRoute
  '/_authenticated/admin/jobs/$slug/edit': typeof AuthenticatedAdminJobsSlugEditRoute
  '/_authenticated/admin/resume-packs/$id/edit': typeof AuthenticatedAdminResumePacksIdEditRoute
  '/_authenticated/admin/resume-templates/$id/edit': typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  '/_authenticated/admin/dmat-complete/$id/': typeof AuthenticatedAdminDmatCompleteIdIndexRoute
  '/_authenticated/admin/dmat-module/$id/': typeof AuthenticatedAdminDmatModuleIdIndexRoute
  '/_authenticated/admin/resume-packs/$id/': typeof AuthenticatedAdminResumePacksIdIndexRoute
  '/_authenticated/admin/resume-templates/$id/': typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/refund-cancellation'
    | '/search'
    | '/sitemap-blog.xml'
    | '/sitemap-core.xml'
    | '/sitemap-hubs.xml'
    | '/sitemap-jobs.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/ats-friendly-resumes/$slug'
    | '/ats-resumes-pack/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/company/$slug'
    | '/jobs/$slug'
    | '/location/$slug'
    | '/resume-bundles/$slug'
    | '/resume-templates/$slug'
    | '/search/admin'
    | '/ats-friendly-resumes/'
    | '/ats-resumes-pack/'
    | '/blog/'
    | '/dmat-resources/'
    | '/resume-bundles/'
    | '/resume-templates/'
    | '/admin/analytics'
    | '/admin/ats-settings'
    | '/admin/feedback'
    | '/admin/orders'
    | '/admin/resume-bundles'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/checkout/bundle/$slug'
    | '/dmat-resources/modules/$slug'
    | '/dmat-resources/packs/$slug'
    | '/payment/success/$orderId'
    | '/admin/'
    | '/dmat-resources/modules/'
    | '/dmat-resources/packs/'
    | '/admin/blog/new'
    | '/admin/dmat-complete/new'
    | '/admin/dmat-module/new'
    | '/admin/jobs/audit'
    | '/admin/jobs/bulk'
    | '/admin/jobs/new'
    | '/admin/resume-packs/new'
    | '/admin/resume-templates/new'
    | '/admin/blog/'
    | '/admin/dmat-complete/'
    | '/admin/dmat-module/'
    | '/admin/resume-packs/'
    | '/admin/resume-templates/'
    | '/admin/blog/$id/edit'
    | '/admin/dmat-complete/$id/edit'
    | '/admin/dmat-module/$id/edit'
    | '/admin/jobs/$slug/edit'
    | '/admin/resume-packs/$id/edit'
    | '/admin/resume-templates/$id/edit'
    | '/admin/dmat-complete/$id/'
    | '/admin/dmat-module/$id/'
    | '/admin/resume-packs/$id/'
    | '/admin/resume-templates/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/refund-cancellation'
    | '/search'
    | '/sitemap-blog.xml'
    | '/sitemap-core.xml'
    | '/sitemap-hubs.xml'
    | '/sitemap-jobs.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/ats-friendly-resumes/$slug'
    | '/ats-resumes-pack/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/company/$slug'
    | '/jobs/$slug'
    | '/location/$slug'
    | '/resume-bundles/$slug'
    | '/resume-templates/$slug'
    | '/search/admin'
    | '/ats-friendly-resumes'
    | '/ats-resumes-pack'
    | '/blog'
    | '/dmat-resources'
    | '/resume-bundles'
    | '/resume-templates'
    | '/admin/analytics'
    | '/admin/ats-settings'
    | '/admin/feedback'
    | '/admin/orders'
    | '/admin/resume-bundles'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/checkout/bundle/$slug'
    | '/dmat-resources/modules/$slug'
    | '/dmat-resources/packs/$slug'
    | '/payment/success/$orderId'
    | '/admin'
    | '/dmat-resources/modules'
    | '/dmat-resources/packs'
    | '/admin/blog/new'
    | '/admin/dmat-complete/new'
    | '/admin/dmat-module/new'
    | '/admin/jobs/audit'
    | '/admin/jobs/bulk'
    | '/admin/jobs/new'
    | '/admin/resume-packs/new'
    | '/admin/resume-templates/new'
    | '/admin/blog'
    | '/admin/dmat-complete'
    | '/admin/dmat-module'
    | '/admin/resume-packs'
    | '/admin/resume-templates'
    | '/admin/blog/$id/edit'
    | '/admin/dmat-complete/$id/edit'
    | '/admin/dmat-module/$id/edit'
    | '/admin/jobs/$slug/edit'
    | '/admin/resume-packs/$id/edit'
    | '/admin/resume-templates/$id/edit'
    | '/admin/dmat-complete/$id'
    | '/admin/dmat-module/$id'
    | '/admin/resume-packs/$id'
    | '/admin/resume-templates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ats-checker'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/refund-cancellation'
    | '/search'
    | '/sitemap-blog.xml'
    | '/sitemap-core.xml'
    | '/sitemap-hubs.xml'
    | '/sitemap-jobs.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/ats-friendly-resumes/$slug'
    | '/ats-resumes-pack/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/company/$slug'
    | '/jobs/$slug'
    | '/location/$slug'
    | '/resume-bundles/$slug'
    | '/resume-templates/$slug'
    | '/search_/admin'
    | '/ats-friendly-resumes/'
    | '/ats-resumes-pack/'
    | '/blog/'
    | '/dmat-resources/'
    | '/resume-bundles/'
    | '/resume-templates/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/ats-settings'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/resume-bundles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/site-settings'
    | '/checkout/bundle/$slug'
    | '/dmat-resources/modules/$slug'
    | '/dmat-resources/packs/$slug'
    | '/payment/success/$orderId'
    | '/_authenticated/admin/'
    | '/dmat-resources/modules/'
    | '/dmat-resources/packs/'
    | '/_authenticated/admin/blog/new'
    | '/_authenticated/admin/dmat-complete/new'
    | '/_authenticated/admin/dmat-module/new'
    | '/_authenticated/admin/jobs/audit'
    | '/_authenticated/admin/jobs/bulk'
    | '/_authenticated/admin/jobs/new'
    | '/_authenticated/admin/resume-packs/new'
    | '/_authenticated/admin/resume-templates/new'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/dmat-complete/'
    | '/_authenticated/admin/dmat-module/'
    | '/_authenticated/admin/resume-packs/'
    | '/_authenticated/admin/resume-templates/'
    | '/_authenticated/admin/blog/$id/edit'
    | '/_authenticated/admin/dmat-complete/$id/edit'
    | '/_authenticated/admin/dmat-module/$id/edit'
    | '/_authenticated/admin/jobs/$slug/edit'
    | '/_authenticated/admin/resume-packs/$id/edit'
    | '/_authenticated/admin/resume-templates/$id/edit'
    | '/_authenticated/admin/dmat-complete/$id/'
    | '/_authenticated/admin/dmat-module/$id/'
    | '/_authenticated/admin/resume-packs/$id/'
    | '/_authenticated/admin/resume-templates/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AtsCheckerRoute: typeof AtsCheckerRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundCancellationRoute: typeof RefundCancellationRoute
  SearchRoute: typeof SearchRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapCoreDotxmlRoute: typeof SitemapCoreDotxmlRoute
  SitemapHubsDotxmlRoute: typeof SitemapHubsDotxmlRoute
  SitemapJobsDotxmlRoute: typeof SitemapJobsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AtsFriendlyResumesSlugRoute: typeof AtsFriendlyResumesSlugRoute
  AtsResumesPackSlugRoute: typeof AtsResumesPackSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CompanySlugRoute: typeof CompanySlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  LocationSlugRoute: typeof LocationSlugRoute
  ResumeBundlesSlugRoute: typeof ResumeBundlesSlugRoute
  ResumeTemplatesSlugRoute: typeof ResumeTemplatesSlugRoute
  SearchAdminRoute: typeof SearchAdminRoute
  AtsFriendlyResumesIndexRoute: typeof AtsFriendlyResumesIndexRoute
  AtsResumesPackIndexRoute: typeof AtsResumesPackIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DmatResourcesIndexRoute: typeof DmatResourcesIndexRoute
  ResumeBundlesIndexRoute: typeof ResumeBundlesIndexRoute
  ResumeTemplatesIndexRoute: typeof ResumeTemplatesIndexRoute
  CheckoutBundleSlugRoute: typeof CheckoutBundleSlugRoute
  DmatResourcesModulesSlugRoute: typeof DmatResourcesModulesSlugRoute
  DmatResourcesPacksSlugRoute: typeof DmatResourcesPacksSlugRoute
  PaymentSuccessOrderIdRoute: typeof PaymentSuccessOrderIdRoute
  DmatResourcesModulesIndexRoute: typeof DmatResourcesModulesIndexRoute
  DmatResourcesPacksIndexRoute: typeof DmatResourcesPacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-jobs.xml': {
      id: '/sitemap-jobs.xml'
      path: '/sitemap-jobs.xml'
      fullPath: '/sitemap-jobs.xml'
      preLoaderRoute: typeof SitemapJobsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-hubs.xml': {
      id: '/sitemap-hubs.xml'
      path: '/sitemap-hubs.xml'
      fullPath: '/sitemap-hubs.xml'
      preLoaderRoute: typeof SitemapHubsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-core.xml': {
      id: '/sitemap-core.xml'
      path: '/sitemap-core.xml'
      fullPath: '/sitemap-core.xml'
      preLoaderRoute: typeof SitemapCoreDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation': {
      id: '/refund-cancellation'
      path: '/refund-cancellation'
      fullPath: '/refund-cancellation'
      preLoaderRoute: typeof RefundCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-checker': {
      id: '/ats-checker'
      path: '/ats-checker'
      fullPath: '/ats-checker'
      preLoaderRoute: typeof AtsCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-templates/': {
      id: '/resume-templates/'
      path: '/resume-templates'
      fullPath: '/resume-templates/'
      preLoaderRoute: typeof ResumeTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-bundles/': {
      id: '/resume-bundles/'
      path: '/resume-bundles'
      fullPath: '/resume-bundles/'
      preLoaderRoute: typeof ResumeBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmat-resources/': {
      id: '/dmat-resources/'
      path: '/dmat-resources'
      fullPath: '/dmat-resources/'
      preLoaderRoute: typeof DmatResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-resumes-pack/': {
      id: '/ats-resumes-pack/'
      path: '/ats-resumes-pack'
      fullPath: '/ats-resumes-pack/'
      preLoaderRoute: typeof AtsResumesPackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-friendly-resumes/': {
      id: '/ats-friendly-resumes/'
      path: '/ats-friendly-resumes'
      fullPath: '/ats-friendly-resumes/'
      preLoaderRoute: typeof AtsFriendlyResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search_/admin': {
      id: '/search_/admin'
      path: '/search/admin'
      fullPath: '/search/admin'
      preLoaderRoute: typeof SearchAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-templates/$slug': {
      id: '/resume-templates/$slug'
      path: '/resume-templates/$slug'
      fullPath: '/resume-templates/$slug'
      preLoaderRoute: typeof ResumeTemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-bundles/$slug': {
      id: '/resume-bundles/$slug'
      path: '/resume-bundles/$slug'
      fullPath: '/resume-bundles/$slug'
      preLoaderRoute: typeof ResumeBundlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/location/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-resumes-pack/$slug': {
      id: '/ats-resumes-pack/$slug'
      path: '/ats-resumes-pack/$slug'
      fullPath: '/ats-resumes-pack/$slug'
      preLoaderRoute: typeof AtsResumesPackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-friendly-resumes/$slug': {
      id: '/ats-friendly-resumes/$slug'
      path: '/ats-friendly-resumes/$slug'
      fullPath: '/ats-friendly-resumes/$slug'
      preLoaderRoute: typeof AtsFriendlyResumesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/dmat-resources/packs/': {
      id: '/dmat-resources/packs/'
      path: '/dmat-resources/packs'
      fullPath: '/dmat-resources/packs/'
      preLoaderRoute: typeof DmatResourcesPacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmat-resources/modules/': {
      id: '/dmat-resources/modules/'
      path: '/dmat-resources/modules'
      fullPath: '/dmat-resources/modules/'
      preLoaderRoute: typeof DmatResourcesModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/payment/success/$orderId': {
      id: '/payment/success/$orderId'
      path: '/payment/success/$orderId'
      fullPath: '/payment/success/$orderId'
      preLoaderRoute: typeof PaymentSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmat-resources/packs/$slug': {
      id: '/dmat-resources/packs/$slug'
      path: '/dmat-resources/packs/$slug'
      fullPath: '/dmat-resources/packs/$slug'
      preLoaderRoute: typeof DmatResourcesPacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmat-resources/modules/$slug': {
      id: '/dmat-resources/modules/$slug'
      path: '/dmat-resources/modules/$slug'
      fullPath: '/dmat-resources/modules/$slug'
      preLoaderRoute: typeof DmatResourcesModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/bundle/$slug': {
      id: '/checkout/bundle/$slug'
      path: '/checkout/bundle/$slug'
      fullPath: '/checkout/bundle/$slug'
      preLoaderRoute: typeof CheckoutBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/site-settings': {
      id: '/_authenticated/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AuthenticatedAdminSiteSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-bundles': {
      id: '/_authenticated/admin/resume-bundles'
      path: '/resume-bundles'
      fullPath: '/admin/resume-bundles'
      preLoaderRoute: typeof AuthenticatedAdminResumeBundlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ats-settings': {
      id: '/_authenticated/admin/ats-settings'
      path: '/ats-settings'
      fullPath: '/admin/ats-settings'
      preLoaderRoute: typeof AuthenticatedAdminAtsSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/': {
      id: '/_authenticated/admin/resume-templates/'
      path: '/resume-templates'
      fullPath: '/admin/resume-templates/'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-packs/': {
      id: '/_authenticated/admin/resume-packs/'
      path: '/resume-packs'
      fullPath: '/admin/resume-packs/'
      preLoaderRoute: typeof AuthenticatedAdminResumePacksIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-module/': {
      id: '/_authenticated/admin/dmat-module/'
      path: '/dmat-module'
      fullPath: '/admin/dmat-module/'
      preLoaderRoute: typeof AuthenticatedAdminDmatModuleIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-complete/': {
      id: '/_authenticated/admin/dmat-complete/'
      path: '/dmat-complete'
      fullPath: '/admin/dmat-complete/'
      preLoaderRoute: typeof AuthenticatedAdminDmatCompleteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/new': {
      id: '/_authenticated/admin/resume-templates/new'
      path: '/resume-templates/new'
      fullPath: '/admin/resume-templates/new'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-packs/new': {
      id: '/_authenticated/admin/resume-packs/new'
      path: '/resume-packs/new'
      fullPath: '/admin/resume-packs/new'
      preLoaderRoute: typeof AuthenticatedAdminResumePacksNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/new': {
      id: '/_authenticated/admin/jobs/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AuthenticatedAdminJobsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/bulk': {
      id: '/_authenticated/admin/jobs/bulk'
      path: '/jobs/bulk'
      fullPath: '/admin/jobs/bulk'
      preLoaderRoute: typeof AuthenticatedAdminJobsBulkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/audit': {
      id: '/_authenticated/admin/jobs/audit'
      path: '/jobs/audit'
      fullPath: '/admin/jobs/audit'
      preLoaderRoute: typeof AuthenticatedAdminJobsAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-module/new': {
      id: '/_authenticated/admin/dmat-module/new'
      path: '/dmat-module/new'
      fullPath: '/admin/dmat-module/new'
      preLoaderRoute: typeof AuthenticatedAdminDmatModuleNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-complete/new': {
      id: '/_authenticated/admin/dmat-complete/new'
      path: '/dmat-complete/new'
      fullPath: '/admin/dmat-complete/new'
      preLoaderRoute: typeof AuthenticatedAdminDmatCompleteNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/new': {
      id: '/_authenticated/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/$id/': {
      id: '/_authenticated/admin/resume-templates/$id/'
      path: '/resume-templates/$id'
      fullPath: '/admin/resume-templates/$id/'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-packs/$id/': {
      id: '/_authenticated/admin/resume-packs/$id/'
      path: '/resume-packs/$id'
      fullPath: '/admin/resume-packs/$id/'
      preLoaderRoute: typeof AuthenticatedAdminResumePacksIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-module/$id/': {
      id: '/_authenticated/admin/dmat-module/$id/'
      path: '/dmat-module/$id'
      fullPath: '/admin/dmat-module/$id/'
      preLoaderRoute: typeof AuthenticatedAdminDmatModuleIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-complete/$id/': {
      id: '/_authenticated/admin/dmat-complete/$id/'
      path: '/dmat-complete/$id'
      fullPath: '/admin/dmat-complete/$id/'
      preLoaderRoute: typeof AuthenticatedAdminDmatCompleteIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/$id/edit': {
      id: '/_authenticated/admin/resume-templates/$id/edit'
      path: '/resume-templates/$id/edit'
      fullPath: '/admin/resume-templates/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-packs/$id/edit': {
      id: '/_authenticated/admin/resume-packs/$id/edit'
      path: '/resume-packs/$id/edit'
      fullPath: '/admin/resume-packs/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminResumePacksIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/$slug/edit': {
      id: '/_authenticated/admin/jobs/$slug/edit'
      path: '/jobs/$slug/edit'
      fullPath: '/admin/jobs/$slug/edit'
      preLoaderRoute: typeof AuthenticatedAdminJobsSlugEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-module/$id/edit': {
      id: '/_authenticated/admin/dmat-module/$id/edit'
      path: '/dmat-module/$id/edit'
      fullPath: '/admin/dmat-module/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminDmatModuleIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dmat-complete/$id/edit': {
      id: '/_authenticated/admin/dmat-complete/$id/edit'
      path: '/dmat-complete/$id/edit'
      fullPath: '/admin/dmat-complete/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminDmatCompleteIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/$id/edit': {
      id: '/_authenticated/admin/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAtsSettingsRoute: typeof AuthenticatedAdminAtsSettingsRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminResumeBundlesRoute: typeof AuthenticatedAdminResumeBundlesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSiteSettingsRoute: typeof AuthenticatedAdminSiteSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
  AuthenticatedAdminDmatCompleteNewRoute: typeof AuthenticatedAdminDmatCompleteNewRoute
  AuthenticatedAdminDmatModuleNewRoute: typeof AuthenticatedAdminDmatModuleNewRoute
  AuthenticatedAdminJobsAuditRoute: typeof AuthenticatedAdminJobsAuditRoute
  AuthenticatedAdminJobsBulkRoute: typeof AuthenticatedAdminJobsBulkRoute
  AuthenticatedAdminJobsNewRoute: typeof AuthenticatedAdminJobsNewRoute
  AuthenticatedAdminResumePacksNewRoute: typeof AuthenticatedAdminResumePacksNewRoute
  AuthenticatedAdminResumeTemplatesNewRoute: typeof AuthenticatedAdminResumeTemplatesNewRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminDmatCompleteIndexRoute: typeof AuthenticatedAdminDmatCompleteIndexRoute
  AuthenticatedAdminDmatModuleIndexRoute: typeof AuthenticatedAdminDmatModuleIndexRoute
  AuthenticatedAdminResumePacksIndexRoute: typeof AuthenticatedAdminResumePacksIndexRoute
  AuthenticatedAdminResumeTemplatesIndexRoute: typeof AuthenticatedAdminResumeTemplatesIndexRoute
  AuthenticatedAdminBlogIdEditRoute: typeof AuthenticatedAdminBlogIdEditRoute
  AuthenticatedAdminDmatCompleteIdEditRoute: typeof AuthenticatedAdminDmatCompleteIdEditRoute
  AuthenticatedAdminDmatModuleIdEditRoute: typeof AuthenticatedAdminDmatModuleIdEditRoute
  AuthenticatedAdminJobsSlugEditRoute: typeof AuthenticatedAdminJobsSlugEditRoute
  AuthenticatedAdminResumePacksIdEditRoute: typeof AuthenticatedAdminResumePacksIdEditRoute
  AuthenticatedAdminResumeTemplatesIdEditRoute: typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  AuthenticatedAdminDmatCompleteIdIndexRoute: typeof AuthenticatedAdminDmatCompleteIdIndexRoute
  AuthenticatedAdminDmatModuleIdIndexRoute: typeof AuthenticatedAdminDmatModuleIdIndexRoute
  AuthenticatedAdminResumePacksIdIndexRoute: typeof AuthenticatedAdminResumePacksIdIndexRoute
  AuthenticatedAdminResumeTemplatesIdIndexRoute: typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAtsSettingsRoute: AuthenticatedAdminAtsSettingsRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminResumeBundlesRoute: AuthenticatedAdminResumeBundlesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSiteSettingsRoute: AuthenticatedAdminSiteSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
  AuthenticatedAdminDmatCompleteNewRoute:
    AuthenticatedAdminDmatCompleteNewRoute,
  AuthenticatedAdminDmatModuleNewRoute: AuthenticatedAdminDmatModuleNewRoute,
  AuthenticatedAdminJobsAuditRoute: AuthenticatedAdminJobsAuditRoute,
  AuthenticatedAdminJobsBulkRoute: AuthenticatedAdminJobsBulkRoute,
  AuthenticatedAdminJobsNewRoute: AuthenticatedAdminJobsNewRoute,
  AuthenticatedAdminResumePacksNewRoute: AuthenticatedAdminResumePacksNewRoute,
  AuthenticatedAdminResumeTemplatesNewRoute:
    AuthenticatedAdminResumeTemplatesNewRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  AuthenticatedAdminDmatCompleteIndexRoute:
    AuthenticatedAdminDmatCompleteIndexRoute,
  AuthenticatedAdminDmatModuleIndexRoute:
    AuthenticatedAdminDmatModuleIndexRoute,
  AuthenticatedAdminResumePacksIndexRoute:
    AuthenticatedAdminResumePacksIndexRoute,
  AuthenticatedAdminResumeTemplatesIndexRoute:
    AuthenticatedAdminResumeTemplatesIndexRoute,
  AuthenticatedAdminBlogIdEditRoute: AuthenticatedAdminBlogIdEditRoute,
  AuthenticatedAdminDmatCompleteIdEditRoute:
    AuthenticatedAdminDmatCompleteIdEditRoute,
  AuthenticatedAdminDmatModuleIdEditRoute:
    AuthenticatedAdminDmatModuleIdEditRoute,
  AuthenticatedAdminJobsSlugEditRoute: AuthenticatedAdminJobsSlugEditRoute,
  AuthenticatedAdminResumePacksIdEditRoute:
    AuthenticatedAdminResumePacksIdEditRoute,
  AuthenticatedAdminResumeTemplatesIdEditRoute:
    AuthenticatedAdminResumeTemplatesIdEditRoute,
  AuthenticatedAdminDmatCompleteIdIndexRoute:
    AuthenticatedAdminDmatCompleteIdIndexRoute,
  AuthenticatedAdminDmatModuleIdIndexRoute:
    AuthenticatedAdminDmatModuleIdIndexRoute,
  AuthenticatedAdminResumePacksIdIndexRoute:
    AuthenticatedAdminResumePacksIdIndexRoute,
  AuthenticatedAdminResumeTemplatesIdIndexRoute:
    AuthenticatedAdminResumeTemplatesIdIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AtsCheckerRoute: AtsCheckerRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  RefundCancellationRoute: RefundCancellationRoute,
  SearchRoute: SearchRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapCoreDotxmlRoute: SitemapCoreDotxmlRoute,
  SitemapHubsDotxmlRoute: SitemapHubsDotxmlRoute,
  SitemapJobsDotxmlRoute: SitemapJobsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AtsFriendlyResumesSlugRoute: AtsFriendlyResumesSlugRoute,
  AtsResumesPackSlugRoute: AtsResumesPackSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CompanySlugRoute: CompanySlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  LocationSlugRoute: LocationSlugRoute,
  ResumeBundlesSlugRoute: ResumeBundlesSlugRoute,
  ResumeTemplatesSlugRoute: ResumeTemplatesSlugRoute,
  SearchAdminRoute: SearchAdminRoute,
  AtsFriendlyResumesIndexRoute: AtsFriendlyResumesIndexRoute,
  AtsResumesPackIndexRoute: AtsResumesPackIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DmatResourcesIndexRoute: DmatResourcesIndexRoute,
  ResumeBundlesIndexRoute: ResumeBundlesIndexRoute,
  ResumeTemplatesIndexRoute: ResumeTemplatesIndexRoute,
  CheckoutBundleSlugRoute: CheckoutBundleSlugRoute,
  DmatResourcesModulesSlugRoute: DmatResourcesModulesSlugRoute,
  DmatResourcesPacksSlugRoute: DmatResourcesPacksSlugRoute,
  PaymentSuccessOrderIdRoute: PaymentSuccessOrderIdRoute,
  DmatResourcesModulesIndexRoute: DmatResourcesModulesIndexRoute,
  DmatResourcesPacksIndexRoute: DmatResourcesPacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
