/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapJobsDotxmlRouteImport } from './routes/sitemap-jobs[.]xml'
import { Route as SitemapHubsDotxmlRouteImport } from './routes/sitemap-hubs[.]xml'
import { Route as SitemapCoreDotxmlRouteImport } from './routes/sitemap-core[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtsCheckerRouteImport } from './routes/ats-checker'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeTemplatesIndexRouteImport } from './routes/resume-templates.index'
import { Route as ResumeBundlesIndexRouteImport } from './routes/resume-bundles.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SearchAdminRouteImport } from './routes/search_.admin'
import { Route as ResumeTemplatesSlugRouteImport } from './routes/resume-templates.$slug'
import { Route as ResumeBundlesSlugRouteImport } from './routes/resume-bundles.$slug'
import { Route as LocationSlugRouteImport } from './routes/location.$slug'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PaymentSuccessOrderIdRouteImport } from './routes/payment.success.$orderId'
import { Route as CheckoutBundleSlugRouteImport } from './routes/checkout.bundle.$slug'
import { Route as AuthenticatedAdminSiteSettingsRouteImport } from './routes/_authenticated/admin.site-settings'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin.feedback'
import { Route as AuthenticatedAdminAtsSettingsRouteImport } from './routes/_authenticated/admin.ats-settings'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminResumeTemplatesIndexRouteImport } from './routes/_authenticated/admin.resume-templates.index'
import { Route as AuthenticatedAdminResumeBundlesIndexRouteImport } from './routes/_authenticated/admin.resume-bundles.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminResumeTemplatesNewRouteImport } from './routes/_authenticated/admin.resume-templates.new'
import { Route as AuthenticatedAdminResumeBundlesNewRouteImport } from './routes/_authenticated/admin.resume-bundles.new'
import { Route as AuthenticatedAdminJobsNewRouteImport } from './routes/_authenticated/admin.jobs.new'
import { Route as AuthenticatedAdminJobsBulkRouteImport } from './routes/_authenticated/admin.jobs.bulk'
import { Route as AuthenticatedAdminJobsAuditRouteImport } from './routes/_authenticated/admin.jobs.audit'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin.blog.new'
import { Route as AuthenticatedAdminResumeTemplatesIdIndexRouteImport } from './routes/_authenticated/admin.resume-templates.$id.index'
import { Route as AuthenticatedAdminResumeBundlesIdIndexRouteImport } from './routes/_authenticated/admin.resume-bundles.$id.index'
import { Route as AuthenticatedAdminResumeTemplatesIdEditRouteImport } from './routes/_authenticated/admin.resume-templates.$id.edit'
import { Route as AuthenticatedAdminResumeBundlesIdEditRouteImport } from './routes/_authenticated/admin.resume-bundles.$id.edit'
import { Route as AuthenticatedAdminJobsSlugEditRouteImport } from './routes/_authenticated/admin.jobs.$slug.edit'
import { Route as AuthenticatedAdminBlogIdEditRouteImport } from './routes/_authenticated/admin.blog.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapJobsDotxmlRoute = SitemapJobsDotxmlRouteImport.update({
  id: '/sitemap-jobs.xml',
  path: '/sitemap-jobs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapHubsDotxmlRoute = SitemapHubsDotxmlRouteImport.update({
  id: '/sitemap-hubs.xml',
  path: '/sitemap-hubs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCoreDotxmlRoute = SitemapCoreDotxmlRouteImport.update({
  id: '/sitemap-core.xml',
  path: '/sitemap-core.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsCheckerRoute = AtsCheckerRouteImport.update({
  id: '/ats-checker',
  path: '/ats-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplatesIndexRoute = ResumeTemplatesIndexRouteImport.update({
  id: '/resume-templates/',
  path: '/resume-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBundlesIndexRoute = ResumeBundlesIndexRouteImport.update({
  id: '/resume-bundles/',
  path: '/resume-bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchAdminRoute = SearchAdminRouteImport.update({
  id: '/search_/admin',
  path: '/search/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplatesSlugRoute = ResumeTemplatesSlugRouteImport.update({
  id: '/resume-templates/$slug',
  path: '/resume-templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBundlesSlugRoute = ResumeBundlesSlugRouteImport.update({
  id: '/resume-bundles/$slug',
  path: '/resume-bundles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/location/$slug',
  path: '/location/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PaymentSuccessOrderIdRoute = PaymentSuccessOrderIdRouteImport.update({
  id: '/payment/success/$orderId',
  path: '/payment/success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutBundleSlugRoute = CheckoutBundleSlugRouteImport.update({
  id: '/checkout/bundle/$slug',
  path: '/checkout/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSiteSettingsRoute =
  AuthenticatedAdminSiteSettingsRouteImport.update({
    id: '/site-settings',
    path: '/site-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAtsSettingsRoute =
  AuthenticatedAdminAtsSettingsRouteImport.update({
    id: '/ats-settings',
    path: '/ats-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesIndexRoute =
  AuthenticatedAdminResumeTemplatesIndexRouteImport.update({
    id: '/resume-templates/',
    path: '/resume-templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeBundlesIndexRoute =
  AuthenticatedAdminResumeBundlesIndexRouteImport.update({
    id: '/resume-bundles/',
    path: '/resume-bundles/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesNewRoute =
  AuthenticatedAdminResumeTemplatesNewRouteImport.update({
    id: '/resume-templates/new',
    path: '/resume-templates/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeBundlesNewRoute =
  AuthenticatedAdminResumeBundlesNewRouteImport.update({
    id: '/resume-bundles/new',
    path: '/resume-bundles/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsNewRoute =
  AuthenticatedAdminJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsBulkRoute =
  AuthenticatedAdminJobsBulkRouteImport.update({
    id: '/jobs/bulk',
    path: '/jobs/bulk',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsAuditRoute =
  AuthenticatedAdminJobsAuditRouteImport.update({
    id: '/jobs/audit',
    path: '/jobs/audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/blog/new',
    path: '/blog/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesIdIndexRoute =
  AuthenticatedAdminResumeTemplatesIdIndexRouteImport.update({
    id: '/resume-templates/$id/',
    path: '/resume-templates/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeBundlesIdIndexRoute =
  AuthenticatedAdminResumeBundlesIdIndexRouteImport.update({
    id: '/resume-bundles/$id/',
    path: '/resume-bundles/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeTemplatesIdEditRoute =
  AuthenticatedAdminResumeTemplatesIdEditRouteImport.update({
    id: '/resume-templates/$id/edit',
    path: '/resume-templates/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResumeBundlesIdEditRoute =
  AuthenticatedAdminResumeBundlesIdEditRouteImport.update({
    id: '/resume-bundles/$id/edit',
    path: '/resume-bundles/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsSlugEditRoute =
  AuthenticatedAdminJobsSlugEditRouteImport.update({
    id: '/jobs/$slug/edit',
    path: '/jobs/$slug/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIdEditRoute =
  AuthenticatedAdminBlogIdEditRouteImport.update({
    id: '/blog/$id/edit',
    path: '/blog/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-hubs.xml': typeof SitemapHubsDotxmlRoute
  '/sitemap-jobs.xml': typeof SitemapJobsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/resume-bundles/$slug': typeof ResumeBundlesSlugRoute
  '/resume-templates/$slug': typeof ResumeTemplatesSlugRoute
  '/search/admin': typeof SearchAdminRoute
  '/blog/': typeof BlogIndexRoute
  '/resume-bundles/': typeof ResumeBundlesIndexRoute
  '/resume-templates/': typeof ResumeTemplatesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/ats-settings': typeof AuthenticatedAdminAtsSettingsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/checkout/bundle/$slug': typeof CheckoutBundleSlugRoute
  '/payment/success/$orderId': typeof PaymentSuccessOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/jobs/audit': typeof AuthenticatedAdminJobsAuditRoute
  '/admin/jobs/bulk': typeof AuthenticatedAdminJobsBulkRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/admin/resume-bundles/new': typeof AuthenticatedAdminResumeBundlesNewRoute
  '/admin/resume-templates/new': typeof AuthenticatedAdminResumeTemplatesNewRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/resume-bundles/': typeof AuthenticatedAdminResumeBundlesIndexRoute
  '/admin/resume-templates/': typeof AuthenticatedAdminResumeTemplatesIndexRoute
  '/admin/blog/$id/edit': typeof AuthenticatedAdminBlogIdEditRoute
  '/admin/jobs/$slug/edit': typeof AuthenticatedAdminJobsSlugEditRoute
  '/admin/resume-bundles/$id/edit': typeof AuthenticatedAdminResumeBundlesIdEditRoute
  '/admin/resume-templates/$id/edit': typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  '/admin/resume-bundles/$id/': typeof AuthenticatedAdminResumeBundlesIdIndexRoute
  '/admin/resume-templates/$id/': typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-hubs.xml': typeof SitemapHubsDotxmlRoute
  '/sitemap-jobs.xml': typeof SitemapJobsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/resume-bundles/$slug': typeof ResumeBundlesSlugRoute
  '/resume-templates/$slug': typeof ResumeTemplatesSlugRoute
  '/search/admin': typeof SearchAdminRoute
  '/blog': typeof BlogIndexRoute
  '/resume-bundles': typeof ResumeBundlesIndexRoute
  '/resume-templates': typeof ResumeTemplatesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/ats-settings': typeof AuthenticatedAdminAtsSettingsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/checkout/bundle/$slug': typeof CheckoutBundleSlugRoute
  '/payment/success/$orderId': typeof PaymentSuccessOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/jobs/audit': typeof AuthenticatedAdminJobsAuditRoute
  '/admin/jobs/bulk': typeof AuthenticatedAdminJobsBulkRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/admin/resume-bundles/new': typeof AuthenticatedAdminResumeBundlesNewRoute
  '/admin/resume-templates/new': typeof AuthenticatedAdminResumeTemplatesNewRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/resume-bundles': typeof AuthenticatedAdminResumeBundlesIndexRoute
  '/admin/resume-templates': typeof AuthenticatedAdminResumeTemplatesIndexRoute
  '/admin/blog/$id/edit': typeof AuthenticatedAdminBlogIdEditRoute
  '/admin/jobs/$slug/edit': typeof AuthenticatedAdminJobsSlugEditRoute
  '/admin/resume-bundles/$id/edit': typeof AuthenticatedAdminResumeBundlesIdEditRoute
  '/admin/resume-templates/$id/edit': typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  '/admin/resume-bundles/$id': typeof AuthenticatedAdminResumeBundlesIdIndexRoute
  '/admin/resume-templates/$id': typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-hubs.xml': typeof SitemapHubsDotxmlRoute
  '/sitemap-jobs.xml': typeof SitemapJobsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/resume-bundles/$slug': typeof ResumeBundlesSlugRoute
  '/resume-templates/$slug': typeof ResumeTemplatesSlugRoute
  '/search_/admin': typeof SearchAdminRoute
  '/blog/': typeof BlogIndexRoute
  '/resume-bundles/': typeof ResumeBundlesIndexRoute
  '/resume-templates/': typeof ResumeTemplatesIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/ats-settings': typeof AuthenticatedAdminAtsSettingsRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/checkout/bundle/$slug': typeof CheckoutBundleSlugRoute
  '/payment/success/$orderId': typeof PaymentSuccessOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/_authenticated/admin/jobs/audit': typeof AuthenticatedAdminJobsAuditRoute
  '/_authenticated/admin/jobs/bulk': typeof AuthenticatedAdminJobsBulkRoute
  '/_authenticated/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/_authenticated/admin/resume-bundles/new': typeof AuthenticatedAdminResumeBundlesNewRoute
  '/_authenticated/admin/resume-templates/new': typeof AuthenticatedAdminResumeTemplatesNewRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/resume-bundles/': typeof AuthenticatedAdminResumeBundlesIndexRoute
  '/_authenticated/admin/resume-templates/': typeof AuthenticatedAdminResumeTemplatesIndexRoute
  '/_authenticated/admin/blog/$id/edit': typeof AuthenticatedAdminBlogIdEditRoute
  '/_authenticated/admin/jobs/$slug/edit': typeof AuthenticatedAdminJobsSlugEditRoute
  '/_authenticated/admin/resume-bundles/$id/edit': typeof AuthenticatedAdminResumeBundlesIdEditRoute
  '/_authenticated/admin/resume-templates/$id/edit': typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  '/_authenticated/admin/resume-bundles/$id/': typeof AuthenticatedAdminResumeBundlesIdIndexRoute
  '/_authenticated/admin/resume-templates/$id/': typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/sitemap-blog.xml'
    | '/sitemap-core.xml'
    | '/sitemap-hubs.xml'
    | '/sitemap-jobs.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/company/$slug'
    | '/jobs/$slug'
    | '/location/$slug'
    | '/resume-bundles/$slug'
    | '/resume-templates/$slug'
    | '/search/admin'
    | '/blog/'
    | '/resume-bundles/'
    | '/resume-templates/'
    | '/admin/analytics'
    | '/admin/ats-settings'
    | '/admin/feedback'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/checkout/bundle/$slug'
    | '/payment/success/$orderId'
    | '/admin/'
    | '/admin/blog/new'
    | '/admin/jobs/audit'
    | '/admin/jobs/bulk'
    | '/admin/jobs/new'
    | '/admin/resume-bundles/new'
    | '/admin/resume-templates/new'
    | '/admin/blog/'
    | '/admin/resume-bundles/'
    | '/admin/resume-templates/'
    | '/admin/blog/$id/edit'
    | '/admin/jobs/$slug/edit'
    | '/admin/resume-bundles/$id/edit'
    | '/admin/resume-templates/$id/edit'
    | '/admin/resume-bundles/$id/'
    | '/admin/resume-templates/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/sitemap-blog.xml'
    | '/sitemap-core.xml'
    | '/sitemap-hubs.xml'
    | '/sitemap-jobs.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/company/$slug'
    | '/jobs/$slug'
    | '/location/$slug'
    | '/resume-bundles/$slug'
    | '/resume-templates/$slug'
    | '/search/admin'
    | '/blog'
    | '/resume-bundles'
    | '/resume-templates'
    | '/admin/analytics'
    | '/admin/ats-settings'
    | '/admin/feedback'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/checkout/bundle/$slug'
    | '/payment/success/$orderId'
    | '/admin'
    | '/admin/blog/new'
    | '/admin/jobs/audit'
    | '/admin/jobs/bulk'
    | '/admin/jobs/new'
    | '/admin/resume-bundles/new'
    | '/admin/resume-templates/new'
    | '/admin/blog'
    | '/admin/resume-bundles'
    | '/admin/resume-templates'
    | '/admin/blog/$id/edit'
    | '/admin/jobs/$slug/edit'
    | '/admin/resume-bundles/$id/edit'
    | '/admin/resume-templates/$id/edit'
    | '/admin/resume-bundles/$id'
    | '/admin/resume-templates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ats-checker'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/sitemap-blog.xml'
    | '/sitemap-core.xml'
    | '/sitemap-hubs.xml'
    | '/sitemap-jobs.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/category/$slug'
    | '/checkout/$slug'
    | '/company/$slug'
    | '/jobs/$slug'
    | '/location/$slug'
    | '/resume-bundles/$slug'
    | '/resume-templates/$slug'
    | '/search_/admin'
    | '/blog/'
    | '/resume-bundles/'
    | '/resume-templates/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/ats-settings'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/site-settings'
    | '/checkout/bundle/$slug'
    | '/payment/success/$orderId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/new'
    | '/_authenticated/admin/jobs/audit'
    | '/_authenticated/admin/jobs/bulk'
    | '/_authenticated/admin/jobs/new'
    | '/_authenticated/admin/resume-bundles/new'
    | '/_authenticated/admin/resume-templates/new'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/resume-bundles/'
    | '/_authenticated/admin/resume-templates/'
    | '/_authenticated/admin/blog/$id/edit'
    | '/_authenticated/admin/jobs/$slug/edit'
    | '/_authenticated/admin/resume-bundles/$id/edit'
    | '/_authenticated/admin/resume-templates/$id/edit'
    | '/_authenticated/admin/resume-bundles/$id/'
    | '/_authenticated/admin/resume-templates/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AtsCheckerRoute: typeof AtsCheckerRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapCoreDotxmlRoute: typeof SitemapCoreDotxmlRoute
  SitemapHubsDotxmlRoute: typeof SitemapHubsDotxmlRoute
  SitemapJobsDotxmlRoute: typeof SitemapJobsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CompanySlugRoute: typeof CompanySlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  LocationSlugRoute: typeof LocationSlugRoute
  ResumeBundlesSlugRoute: typeof ResumeBundlesSlugRoute
  ResumeTemplatesSlugRoute: typeof ResumeTemplatesSlugRoute
  SearchAdminRoute: typeof SearchAdminRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ResumeBundlesIndexRoute: typeof ResumeBundlesIndexRoute
  ResumeTemplatesIndexRoute: typeof ResumeTemplatesIndexRoute
  CheckoutBundleSlugRoute: typeof CheckoutBundleSlugRoute
  PaymentSuccessOrderIdRoute: typeof PaymentSuccessOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-jobs.xml': {
      id: '/sitemap-jobs.xml'
      path: '/sitemap-jobs.xml'
      fullPath: '/sitemap-jobs.xml'
      preLoaderRoute: typeof SitemapJobsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-hubs.xml': {
      id: '/sitemap-hubs.xml'
      path: '/sitemap-hubs.xml'
      fullPath: '/sitemap-hubs.xml'
      preLoaderRoute: typeof SitemapHubsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-core.xml': {
      id: '/sitemap-core.xml'
      path: '/sitemap-core.xml'
      fullPath: '/sitemap-core.xml'
      preLoaderRoute: typeof SitemapCoreDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-checker': {
      id: '/ats-checker'
      path: '/ats-checker'
      fullPath: '/ats-checker'
      preLoaderRoute: typeof AtsCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-templates/': {
      id: '/resume-templates/'
      path: '/resume-templates'
      fullPath: '/resume-templates/'
      preLoaderRoute: typeof ResumeTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-bundles/': {
      id: '/resume-bundles/'
      path: '/resume-bundles'
      fullPath: '/resume-bundles/'
      preLoaderRoute: typeof ResumeBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search_/admin': {
      id: '/search_/admin'
      path: '/search/admin'
      fullPath: '/search/admin'
      preLoaderRoute: typeof SearchAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-templates/$slug': {
      id: '/resume-templates/$slug'
      path: '/resume-templates/$slug'
      fullPath: '/resume-templates/$slug'
      preLoaderRoute: typeof ResumeTemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-bundles/$slug': {
      id: '/resume-bundles/$slug'
      path: '/resume-bundles/$slug'
      fullPath: '/resume-bundles/$slug'
      preLoaderRoute: typeof ResumeBundlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/location/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/payment/success/$orderId': {
      id: '/payment/success/$orderId'
      path: '/payment/success/$orderId'
      fullPath: '/payment/success/$orderId'
      preLoaderRoute: typeof PaymentSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/bundle/$slug': {
      id: '/checkout/bundle/$slug'
      path: '/checkout/bundle/$slug'
      fullPath: '/checkout/bundle/$slug'
      preLoaderRoute: typeof CheckoutBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/site-settings': {
      id: '/_authenticated/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AuthenticatedAdminSiteSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ats-settings': {
      id: '/_authenticated/admin/ats-settings'
      path: '/ats-settings'
      fullPath: '/admin/ats-settings'
      preLoaderRoute: typeof AuthenticatedAdminAtsSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/': {
      id: '/_authenticated/admin/resume-templates/'
      path: '/resume-templates'
      fullPath: '/admin/resume-templates/'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-bundles/': {
      id: '/_authenticated/admin/resume-bundles/'
      path: '/resume-bundles'
      fullPath: '/admin/resume-bundles/'
      preLoaderRoute: typeof AuthenticatedAdminResumeBundlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/new': {
      id: '/_authenticated/admin/resume-templates/new'
      path: '/resume-templates/new'
      fullPath: '/admin/resume-templates/new'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-bundles/new': {
      id: '/_authenticated/admin/resume-bundles/new'
      path: '/resume-bundles/new'
      fullPath: '/admin/resume-bundles/new'
      preLoaderRoute: typeof AuthenticatedAdminResumeBundlesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/new': {
      id: '/_authenticated/admin/jobs/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AuthenticatedAdminJobsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/bulk': {
      id: '/_authenticated/admin/jobs/bulk'
      path: '/jobs/bulk'
      fullPath: '/admin/jobs/bulk'
      preLoaderRoute: typeof AuthenticatedAdminJobsBulkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/audit': {
      id: '/_authenticated/admin/jobs/audit'
      path: '/jobs/audit'
      fullPath: '/admin/jobs/audit'
      preLoaderRoute: typeof AuthenticatedAdminJobsAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/new': {
      id: '/_authenticated/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/$id/': {
      id: '/_authenticated/admin/resume-templates/$id/'
      path: '/resume-templates/$id'
      fullPath: '/admin/resume-templates/$id/'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-bundles/$id/': {
      id: '/_authenticated/admin/resume-bundles/$id/'
      path: '/resume-bundles/$id'
      fullPath: '/admin/resume-bundles/$id/'
      preLoaderRoute: typeof AuthenticatedAdminResumeBundlesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-templates/$id/edit': {
      id: '/_authenticated/admin/resume-templates/$id/edit'
      path: '/resume-templates/$id/edit'
      fullPath: '/admin/resume-templates/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminResumeTemplatesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resume-bundles/$id/edit': {
      id: '/_authenticated/admin/resume-bundles/$id/edit'
      path: '/resume-bundles/$id/edit'
      fullPath: '/admin/resume-bundles/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminResumeBundlesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/$slug/edit': {
      id: '/_authenticated/admin/jobs/$slug/edit'
      path: '/jobs/$slug/edit'
      fullPath: '/admin/jobs/$slug/edit'
      preLoaderRoute: typeof AuthenticatedAdminJobsSlugEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/$id/edit': {
      id: '/_authenticated/admin/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAtsSettingsRoute: typeof AuthenticatedAdminAtsSettingsRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSiteSettingsRoute: typeof AuthenticatedAdminSiteSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
  AuthenticatedAdminJobsAuditRoute: typeof AuthenticatedAdminJobsAuditRoute
  AuthenticatedAdminJobsBulkRoute: typeof AuthenticatedAdminJobsBulkRoute
  AuthenticatedAdminJobsNewRoute: typeof AuthenticatedAdminJobsNewRoute
  AuthenticatedAdminResumeBundlesNewRoute: typeof AuthenticatedAdminResumeBundlesNewRoute
  AuthenticatedAdminResumeTemplatesNewRoute: typeof AuthenticatedAdminResumeTemplatesNewRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminResumeBundlesIndexRoute: typeof AuthenticatedAdminResumeBundlesIndexRoute
  AuthenticatedAdminResumeTemplatesIndexRoute: typeof AuthenticatedAdminResumeTemplatesIndexRoute
  AuthenticatedAdminBlogIdEditRoute: typeof AuthenticatedAdminBlogIdEditRoute
  AuthenticatedAdminJobsSlugEditRoute: typeof AuthenticatedAdminJobsSlugEditRoute
  AuthenticatedAdminResumeBundlesIdEditRoute: typeof AuthenticatedAdminResumeBundlesIdEditRoute
  AuthenticatedAdminResumeTemplatesIdEditRoute: typeof AuthenticatedAdminResumeTemplatesIdEditRoute
  AuthenticatedAdminResumeBundlesIdIndexRoute: typeof AuthenticatedAdminResumeBundlesIdIndexRoute
  AuthenticatedAdminResumeTemplatesIdIndexRoute: typeof AuthenticatedAdminResumeTemplatesIdIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAtsSettingsRoute: AuthenticatedAdminAtsSettingsRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSiteSettingsRoute: AuthenticatedAdminSiteSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
  AuthenticatedAdminJobsAuditRoute: AuthenticatedAdminJobsAuditRoute,
  AuthenticatedAdminJobsBulkRoute: AuthenticatedAdminJobsBulkRoute,
  AuthenticatedAdminJobsNewRoute: AuthenticatedAdminJobsNewRoute,
  AuthenticatedAdminResumeBundlesNewRoute:
    AuthenticatedAdminResumeBundlesNewRoute,
  AuthenticatedAdminResumeTemplatesNewRoute:
    AuthenticatedAdminResumeTemplatesNewRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  AuthenticatedAdminResumeBundlesIndexRoute:
    AuthenticatedAdminResumeBundlesIndexRoute,
  AuthenticatedAdminResumeTemplatesIndexRoute:
    AuthenticatedAdminResumeTemplatesIndexRoute,
  AuthenticatedAdminBlogIdEditRoute: AuthenticatedAdminBlogIdEditRoute,
  AuthenticatedAdminJobsSlugEditRoute: AuthenticatedAdminJobsSlugEditRoute,
  AuthenticatedAdminResumeBundlesIdEditRoute:
    AuthenticatedAdminResumeBundlesIdEditRoute,
  AuthenticatedAdminResumeTemplatesIdEditRoute:
    AuthenticatedAdminResumeTemplatesIdEditRoute,
  AuthenticatedAdminResumeBundlesIdIndexRoute:
    AuthenticatedAdminResumeBundlesIdIndexRoute,
  AuthenticatedAdminResumeTemplatesIdIndexRoute:
    AuthenticatedAdminResumeTemplatesIdIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AtsCheckerRoute: AtsCheckerRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapCoreDotxmlRoute: SitemapCoreDotxmlRoute,
  SitemapHubsDotxmlRoute: SitemapHubsDotxmlRoute,
  SitemapJobsDotxmlRoute: SitemapJobsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CompanySlugRoute: CompanySlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  LocationSlugRoute: LocationSlugRoute,
  ResumeBundlesSlugRoute: ResumeBundlesSlugRoute,
  ResumeTemplatesSlugRoute: ResumeTemplatesSlugRoute,
  SearchAdminRoute: SearchAdminRoute,
  BlogIndexRoute: BlogIndexRoute,
  ResumeBundlesIndexRoute: ResumeBundlesIndexRoute,
  ResumeTemplatesIndexRoute: ResumeTemplatesIndexRoute,
  CheckoutBundleSlugRoute: CheckoutBundleSlugRoute,
  PaymentSuccessOrderIdRoute: PaymentSuccessOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
