// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  try {
    console.error("[DEBUG] Starting createSupabaseClient");
    // import.meta.env is only available in Vite client bundles.
    // On the server (Nitro SSR), fall back to process.env.
    const metaEnv =
      typeof import.meta !== "undefined"
        ? (import.meta as any).env
        : {};

    const SUPABASE_URL =
      metaEnv?.VITE_SUPABASE_URL || process.env.SUPABASE_URL;

    const SUPABASE_PUBLISHABLE_KEY =
      metaEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
    console.error("[DEBUG] createSupabaseClient complete");
    return client;
  } catch (err: any) {
    console.error("[DEBUG] SSR CRASH in createSupabaseClient:", err.message);
    console.error("[DEBUG] Stack:", err.stack);
    throw err;
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

